[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
#requires = ["hatchling"]
#build-backend = "hatchling.build"

#[project]
##name = "station-climate-etl-ipfs"
#name = "example_package"
#version = "0.0.1"
#description = "A system which does something"
#readme = "README.md"
#requires-python = ">=3.8.3"
#classifiers = [
#    "Programming Language :: Python :: 3",
#    "License :: OSI Approved :: MIT License",
#    "Operating System :: OS Independent",
#]
#dependencies = [
#  "click>=8.0.3",
#  "hatchling>=1.11.0",
#  "httpx>=0.22.0",
#  "hyperlink>=21.0.0",
#  "keyring>=23.5.0",
#  "packaging>=21.3",
#  "pexpect~=4.8",
#  "platformdirs>=2.5.0",
#  "pyperclip>=1.8.2",
#  "rich>=11.2.0",
#  "shellingham>=1.4.0",
#  "tomli-w>=1.0",
#  "tomlkit>=0.11.1",
#  "userpath~=1.7",
#  "virtualenv>=20.16.2",
#]

#[project.urls]
#"Homepage" = "https://github.com/Arbol-Project/station-climate-etl-ipfs"
#"Bug Tracker" = "https://github.com/Arbol-Project/station-climate-etl-ipfs/issues"