name: Trigger to build prefect-etl-orchestration workflow for gridded ETL containers
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dispatch:
    name: Dispatch workflow in prefect-etl-orchestration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['Arbol-Project/prefect-etl-orchestration']
    timeout-minutes: 5
    steps:
      - name: Create new virtual env and install packages for python
        uses: actions/checkout@v4
        run: |
              cd nettle
              python3.8 -m venv ./chiquititas
              source chiquititas/bin/activate
              pip install -r requirements.txt
              pip install .

      - name: Run unit tests
        run: python3.8 -m unittest
#      - name: Dispatch to workflows
#        run: |
#            curl -X POST https://api.github.com/repos/${{ matrix.repo }}/dispatches \
#            -H "Accept: application/vnd.github.everest-preview+json" \
#            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
#            --data '{"event_type": "non-gridded-build", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }'
