name: Trigger to build prefect-etl-orchestration workflow for gridded ETL containers
on:
  push:
    branches: [main, actions_unittests]
  workflow_dispatch:

jobs:
  dispatch:
    name: Dispatch workflow in prefect-etl-orchestration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['Arbol-Project/prefect-etl-orchestration']
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: nettle

      - name: Add mock profile credentials to ~/.aws/credentials
         run: |
            aws configure set aws_access_key_id foo --profile arbol-dev
            aws configure set aws_secret_access_key bar --profile arbol-dev
            aws configure set region us-west-2 --profile arbol-dev

      - name: Create new virtual env and install packages for python
        run: |
              cd nettle
              python -m venv ./chiquititas
              source chiquititas/bin/activate
              pip install -r requirements.txt
              pip install .
              pip list
              python -m unittest

#      - name: Run unit tests
#        run: python -m unittest
#        working-directory: nettle
#      - name: Dispatch to workflows
#        run: |
#            curl -X POST https://api.github.com/repos/${{ matrix.repo }}/dispatches \
#            -H "Accept: application/vnd.github.everest-preview+json" \
#            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
#            --data '{"event_type": "non-gridded-build", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }'
#
